version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install poetry-plugin-export
      - poetry export --extras docs -f requirements.txt --output requirements.txt --without-hashes

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: src/docs/conf.py