name: docs

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install rye
        uses: eifinger/setup-rye@v1

      - name: Load cached venv
        id: cached-venv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-doc-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        if: steps.cached-venv-dependencies.outputs.cache-hit != 'true'
        run: |
          pip install dunamai
          VERSION=$(dunamai from any --no-metadata --style pep440)
          rye version $VERSION
          rye sync --no-dev --features docs

      - name: Create docs
        run: |
          rye run html